services:
  # nginx
  apartment-nginx:
    container_name: apartment-nginx
    image: nginx:stable-alpine
    ports:
      - "6050:80"
    volumes:
      - ./src:/var/www/apartment
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apartment-php
      - apartment-mariadb
    networks:
      - apartment

  #php
  apartment-php:
    container_name: apartment-php
    build:
      context: .
      dockerfile: ./_docker/php/php.dockerfile
    volumes:
      - ./src/:/var/www/apartment
      - ./_docker/php/php.ini:/usr/local/etc/php/php.ini
    command: php-fpm

    depends_on:
      - apartment-mariadb
    ports:
      - "6051:5051"
      - "5173:5173"
    networks:
      - apartment

  #mariadb
  apartment-mariadb:
    container_name: apartment-mariadb
    image: mariadb:latest
    ports:
      - "6052:3306"
    volumes:
      - ./_docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: apartment
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - apartment

  apartment-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - apartment-mariadb:db
    restart: always
    ports:
      - "6054:80"
    environment:
      UPLOAD_LIMIT: 500M
      PMA_ARBITRARY: 1
    networks:
      - apartment

networks:
  apartment:
